server:
  port: 8081

spring:
  application:
    name: eduquest-backend
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/eduquest_v2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  jwt:
    secret: EduQuestV2SuperSecretKeyForJWTAuthTokenGenerationAndSigning9876543210
    expiration-ms: 86400000 # 24 hours
